name: Generate workflows
on:
  push:
    branches:
      - main
    paths:
      - ".github/real-workflows/*.yml"
  workflow_dispatch:
jobs:
  generate-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Run locally
        uses: 'DanySK/true-yaml-actions@1.0.3' # pick the latest version maybe
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
