name: Generate workflows
on:
  push:
    branches:
      - main
    paths:
      - ".github/real-workflows/*.yml"
jobs:
  generate-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Run locally
        uses: 'DanySK/true-yaml-actions@1.0.3' # pick the latest version maybe
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Run newly created workflow
        uses: 'Terutsa97/Converted-UPM/.github/workflows/ci.yml@main'
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
